[project]
name = "passport_management"
version = "1.0.0"
description = "Passport Movement Management for ERPNext"
requires-python = ">=3.10"
readme = "README.md"
dependencies = []

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "passport_management"
